# Generated by Django 4.2.5 on 2023-10-07 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnail')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('type_of_collaborator', models.CharField(blank=True, max_length=250, null=True)),
                ('level_of_expertise_of_collaborator', models.CharField(blank=True, max_length=250, null=True)),
                ('domain', models.CharField(blank=True, max_length=250, null=True)),
                ('tech_stack', models.JSONField(blank=True, encoder=json.encoder.JSONEncoder, null=True)),
                ('github_link', models.CharField(blank=True, max_length=250, null=True)),
                ('tasks', models.JSONField(blank=True, encoder=json.encoder.JSONEncoder, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
