# Generated by Django 4.2.5 on 2023-10-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='email',
        ),
    ]
