# Generated by Django 4.2.5 on 2023-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_author_project_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='txt',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='level_of_expertise_of_collaborator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type_of_collaborator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
