# Generated by Django 4.2.2 on 2023-09-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='full_name',
        ),
    ]
